-- Personalized setup for: user GATOR, warehouse GATOR_WH, database GATOR_DB, schema MY_SCHEMA
-- Run blocks in order. If USE ROLE SYSADMIN fails, skip to the TRAINING_ROLE block

-- [Admin block] Create objects with a privileged role (if available)
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS GATOR_WH
  WITH WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS GATOR_DB;
CREATE SCHEMA IF NOT EXISTS GATOR_DB.MY_SCHEMA;

GRANT USAGE ON WAREHOUSE GATOR_WH TO ROLE TRAINING_ROLE;
GRANT USAGE ON DATABASE GATOR_DB TO ROLE TRAINING_ROLE;
GRANT USAGE ON SCHEMA GATOR_DB.MY_SCHEMA TO ROLE TRAINING_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA GATOR_DB.MY_SCHEMA TO ROLE TRAINING_ROLE;

-- Switch to working role and set context
USE ROLE TRAINING_ROLE;
USE WAREHOUSE GATOR_WH;
USE DATABASE GATOR_DB;
USE SCHEMA MY_SCHEMA;

-- Set user defaults (idempotent-style; safe to rerun)
ALTER USER GATOR SET
  DEFAULT_WAREHOUSE = GATOR_WH,
  DEFAULT_NAMESPACE = GATOR_DB.MY_SCHEMA,
  DEFAULT_ROLE = TRAINING_ROLE;

-- Verify context
SELECT CURRENT_ROLE() AS ROLE,
       CURRENT_WAREHOUSE() AS WAREHOUSE,
       CURRENT_DATABASE() AS DATABASE,
       CURRENT_SCHEMA() AS SCHEMA;

-- Temp table (fully-qualified to avoid context confusion)
CREATE OR REPLACE TEMPORARY TABLE GATOR_DB.MY_SCHEMA.MY_FAVORITE_ACTORS (NAME VARCHAR);

INSERT INTO GATOR_DB.MY_SCHEMA.MY_FAVORITE_ACTORS (NAME) VALUES
  ('Heath Ledger'),
  ('Michelle Pfeiffer'),
  ('Meryl Streep'),
  ('Anthony Hopkins'),
  ('Bruce Lee');

SELECT * FROM GATOR_DB.MY_SCHEMA.MY_FAVORITE_ACTORS;

-- Optional: sample dataset queries (requires SNOWBEARAIR_DB)
-- SHOW TABLES;
-- SELECT * FROM SNOWBEARAIR_DB.MODELED.MEMBERS LIMIT 10;
